import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

/**
 * TypeORM entity - user account
 */
@Entity()
export class User {
    /** Unique ID - autogenerated */
    @PrimaryGeneratedColumn({ type: "int" })
    id: number;
    /** Email */
    @Column({ type: "varchar", length: 256 })
    email: string;
    /** Hash of the user password with salt and pepper */
    @Column({ type: "varchar", length: 512 })
    passwordHash: string;
    /** Salt used in password hash */
    @Column({ type: "varchar", length: 32 })
    salt: string;
}